init:
  - git config --global core.autocrlf input

os: Visual Studio 2015

platform:
  - x86
  - x64

install:
  - set PATH=C:\cygwin\bin;%PATH%
  - appveyor DownloadFile "http://raw.githubusercontent.com/swig/cccl/master/cccl"
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%

build_script:
  - sh --login /cygdrive/c/projects/sauce/scripts/appveyor

test: off
deploy: off
